### ISSUE TITLE
Super Jump and/or Super Climb crashes server.

### ISSUE THREAD

**Issue by Wertlos** [Hokuten85/Ivalice#10]
Used Super Jump on an idle, unengaged target with wyvern out.

**Comment by Hokuten85** [comment]
https://github.com/DarkstarProject/darkstar/issues/3515

there is a function call in super_jump.lau that's "stunning" the character for 5 seconds, and it's causing the server crash.  I've removed that line from the script and it's no longer crashing.  I'll wait for DSP to dig further into the issue and let them fix it.

Also, I made some tweaks to how my system handles crash dumps.  The UI notification of a crash is hidden.  This should allow the server to auto restart on all crashes will still capturing the crash dumps
