### ISSUE TITLE
Fully Boosted Chi Blast did zero damage

### ISSUE THREAD

**Issue by Hokuten85** [Hokuten85/Ivalice#4]
WTF!? Fully Boosted Chi Blast did shit... what did you dooooo!?!?!

**Comment by Wertlos** [comment]
Using Chi Blast while having the Boost status active results in Chi Blast dealing 0 damage and leaves the target unclaimed and unaggroed. The Boost status stays active after using Chi Blast.

**Comment by Hokuten85** [comment]
Chi blast needs to be 2:30 as well

**Comment by Hokuten85** [comment]
fixed
